workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - android_credentials
      vars:
        PACKAGE_NAME: "com.gtasa.skinmanager"
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Install Gradle 8.2
        script: |
          wget https://services.gradle.org/distributions/gradle-8.2-bin.zip
          unzip -q gradle-8.2-bin.zip
          export PATH=$PWD/gradle-8.2/bin:$PATH
      - name: Build Android Debug APK
        script: |
          export PATH=$PWD/gradle-8.2/bin:$PATH
          gradle assembleDebug --no-daemon --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - bzns4665@gmail.com
        notify:
          success: true
          failure: true
